branches:
  except:
  - master
language: node_js
node_js:
- node
pre_install:
- ulimit -n 8192
install:
- echo "Building for tests"
- yarn run build:test
script:
- echo "Starting tests"
- yarn run test
after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
env:
  global:
  - secure: qFhOvTuwwLIF3wr4v/P8CnkOTD9itFE7XpaJuBIzYYb5uGJrtDbyEnmuuPb3E0GKJcdOYwGD2f1UyMhEtQEXxuz39XRAFNrp/zv5Va7f+/f5WiwaUMoxt/XRZZkRq2cfeET0j8tSC/tHpymkiWRv2OCSlVqBd+wbd+n5rJn1svSEf6b2WurYN7syAmLK92y1LQ/RN3IQYk0ojfeoNPO5XXPhw8NASN4CxyrPu0emZCpK/9z8kTMZKbQpkCayO8NPJN/Lb9N8+WTIZygIx/OSm8WywWNj5b29FBBe+bH2PprT2PZXz1176yu9PQeSYbuSGAKjlq3LK6iO0zWTsHAKOHEdTpdHTCsJEycvxq4h9JKWrrGK8NXYzdjn4O09v9mdrA4j3geMmUhxQ0E1t+Naq35oyXwNBsaeHzu8SPR4H6Jttwg8sZgqEXtRrhWjkfp7UvXk411yToyay+UQ6iuBJ4G7LKG729BNPkrHWo3p0tngZlvT5hbfgTdZ6C1jOzdymYPi+vU8cgOf56fuSUXzHY/VQcPULB42v/1GuGxiIlE0DqtJLKAuxwFlqOCGpUKOOxN4FuLmz5PTTYJZxTtano0bjlz4sCq6hwf6gTWXCOPPJDnxIeXgKhsPlV6Gn9gZCulb93JMjN4mKrtqIA8nPOYIBTjys721XWj1Nnd2GmU=
  - secure: kx9npS2LzS3HhdeYbKkc+Q8nWWqyRzuZWFFcntygtRMe1xTXbTJXPhlQR1lvqJzpkqK1ip092N3IbktUPF2RFwqDo2krmZxnBHDez7uFjyT67Hx5bsGOGg8A8el4c9TsX4Ql9vc689QXNASBCZhX29LPG9Y7JpND2b4EDUPQoeYC9EulEXYDclTb1dTkzxTWis4LoIfkb0YsDWwrWu8v6IQl24S6qyuorwXvxhLvK4gWCYGqoB7SM8kLOivsLYc9JDEIbIiaYyOnk9x6o0QnMZydIGn1ti89eBxmXG5yVWSkRfA53CHvKuKh1gMwMWBg+Bb46R1ad4vmlJ3yuyk4J0Qy7lHwidoEHFnH9LWz1bnyp0evoRbnuHOIfIPJS15xgoTFcHuzYZVOrijMDJl/GpUy6+b5jwBNPavmcg+kAQlQLyMtq6rUwWrkuaDWSiBUIrAscGBYJ8PiT0/xXkJ+2AfOR/mF7Ggo5NMhtVvkfuNtYZ/mrfK04dstNmZ8Yu1qPIcXPa1o2AHc053wU01VZdFhzyfXQWIcPmacMpCiI8Zu9iG/NgOsvZAbwU+5Y21+VWgtm5HN9ITgPqW5tpID8nsNu6Ky9Yf+/t5XbVqJ73fR1GXOC0z4uI4eYFTYvuOIp5m0+cPCqr2B05d2Lqj0Tpu37g/P8JBej3/J+zsfqhc=
