language: node_js

before_install:
  - echo "Installing yarn"
  - npm install -g yarn

install:
  - echo "Building for tests"
  - yarn run build:test

script:
  - echo "Starting tests"
  - yarn run test

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
